spring:
  datasource:
    password:
    username: sa
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop